### ISSUE TITLE
sfmc.rest.post jsonPayload validation doesn't allow for [object Array]

### ISSUE THREAD

**Issue by mekadigital** [DougMidgley/SFMC-SDK#101]
Hi,

I am using the sdk to sync records into a DE which takes a payload of an array of objects. This errors as the type of the payload is [object Array] and not [object Object] which is validated in util.js

I'll add a pull request to update the validation shortly.

`
const records = [{
    keys: {
      customerID: '1234'
    },
    values: {
      email: 'test@example.com'
    }
  }]
await sfmcClient.rest.post(`/hub/v1/dataevents/key:${customerDe}/rowset`, records)
`

Thanks for rebuilding this library, is a real life saver.

**Comment by DougMidgley** [comment]
Hey @mekadigital thanks for the input :) this method is intended to really check for objects not arrays, for that the Array.isArray([1,2]) method exists. I'm open to adding this in specific cases, for example on the REST payload validation if its useful, but would want to avoid extending isObject to include Arrays.

**Comment by mekadigital** [comment]
Hey @DougMidgley thats cool. I've created a new pull request up that adds a isPayload function instead that does the check only and a test function for coverage

**Comment by DougMidgley** [comment]
released v0.6 :)
