### ISSUE TITLE
getAccessToken() in the auth.js

### ISSUE THREAD

**Issue by hunghua** [DougMidgley/SFMC-SDK#134]
The _isExpired(this.authObject) always returns true (line 155 in auth.js).

**Comment by DougMidgley** [comment]
Hey @hunghua  - do you have some examples of what you are sending in? this.authObject?

**Comment by hunghua** [comment]
Hi @DougMidgley 

This is the code that i tested and saw that i always run the _requestToken(this.authObject) (line 158 in auth.js)

![image](https://user-images.githubusercontent.com/12770987/196311383-21a6d757-f119-4df4-8b5f-84a426543170.png)
![image](https://user-images.githubusercontent.com/12770987/196311444-e348b62f-2c0c-498b-a750-269200a87429.png)
