### ISSUE TITLE
Auth /v2/token  error occurs when invoking functions

### ISSUE THREAD

**Issue by rain89146** [DougMidgley/SFMC-SDK#218]
it looks like salesforce is slowly sunsetting the /v2/token, and going with /v1/requesttoken. please update the auth method accordingly.

**Comment by DougMidgley** [comment]
Hey @rain89146  thanks for input! I had a look around but couldnt see anything as per your suggestion? https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/requestToken.html does have some details but this is for old OAuth1 packages. OAuth2 packages use v2/token (https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/access-token-s2s.html) normally. Let me know if I missed something :)

**Comment by DougMidgley** [comment]
Closing issue as seems not blocking/no feedback additional
