### ISSUE TITLE
Missing Best Man

### ISSUE THREAD

**Issue by DougMidgley** [DougMidgley/SFMC-SDK#246]
Currently there is a vacancy at the lead contributors September 3rd event - assignee is requested to consider patching this issue by filling the best man role.

**Comment by JoernBerkefeld** [comment]
issue closed as part of release of new package _Marriage_ v1.0.0 in Sep 2023.
I expect future patch releases and potentially new _features_ in a couple years but don't want to work on a new major release for that package.
