### ISSUE TITLE
hyphens should be considered valid in auth_url

### ISSUE THREAD

**Issue by michaelt-offprem** [DougMidgley/SFMC-SDK#263]
lib/auth.js line 48 tests for valid auth_url

Issue: valid auth URLs should allow hyphens

Consider changing to:
```js
                !/https:\/\/[a-z0-9-]{28}\.auth\.marketingcloudapis\.com\//gm.test(options.auth_url)
```

**Comment by DougMidgley** [comment]
Hey @michaelt-offprem 
https://github.com/DougMidgley/SFMC-SDK/blob/c9c364806342628e77c0f459c18185065b072c11/lib/auth.js#L126 is checking for dash/hyphen also (\d is digit, a-z does character, - is dash).
Line 48 of auth.js (in current version) isn't doing any checks.
Let me know if something more you need!

**Comment by michaelt-offprem** [comment]
@DougMidgley Ah! Thanks. I see that now - I was looking at the local copy in my node_modules - which wasn't the latest 2.0.1 - just reinstalled the npm package (which was recently updated to 2.0.1 looks like) and that's resolved it. Sorry for the spurious issue here!
