### ISSUE TITLE
Allow adding headers for POST/PUT and PATCH REST request

### ISSUE THREAD

**Issue by phjulia** [DougMidgley/SFMC-SDK#285]
Some Marketing Cloud API Endpoints require additional headers. 
Example:
https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/downloadJourneyHistory.html
Extend existing functions for POST/PUT and PATCH requests to allow adding additional headers

P.S. I'll submit a PR

**Comment by JoernBerkefeld** [comment]
given that it wasnt merged i'll reopen this ticket

**Comment by JoernBerkefeld** [comment]
closed by #307
