### ISSUE TITLE
Soap request to create a Data Extension failing

### ISSUE THREAD

**Issue by ivanrazine** [DougMidgley/SFMC-SDK#299]
Hey Doug,

I've been trying to use your package to perform a SOAP request to create a new Data Extension, but it fails because the XML generated by the code ignores the "Fields" parameter.

I'm suspecting that your logic doesn't support arrays as values for the params, does it? 

```
const result = await sfmc.soap.create(
      'DataExtension', 
      {
          "CustomerKey": "DA395430-B616-11EE-8162-0F78DFCCB487",
          "Name": "Customers_v3 DA395430-B616-11EE-8162-0F78DFCCB487",
          "IsSendable": false,
          "IsTestable": false,
          "CategoryID": 3123,
          "Fields": [
            {
              "Name": "CreatedDate",
              "IsRequired": false,
              "Ordinal": 2,
              "IsPrimaryKey": false,
              "FieldType": "Date"
            },
            {
              "Name": "DeeplinkURL",
              "MaxLength": 50,
              "IsRequired": false,
              "Ordinal": 1,
              "IsPrimaryKey": false,
              "FieldType": "Text"
            },
            {
              "Name": "SubscriberKey",
              "MaxLength": 50,
              "IsRequired": false,
              "Ordinal": 0,
              "IsPrimaryKey": false,
              "FieldType": "Text"
            }
          ]
      },
      {
          options: {
              SaveOptions: { SaveAction: 'UpdateAdd' },
          },
      }
  )`

**Comment by ivanrazine** [comment]
Found a solution.

**fast-xml-parser** has a certain way it expects the JSON to be structured.

Therefore, if we want to create sub-nodes in XML, this is the way:

```
"Fields": {
    "Field": [
        {
            "Name": "CreatedDate",
            "IsRequired": false,
            "Ordinal": 2,
            "IsPrimaryKey": false,
            "FieldType": "Date"
        }
    ]
}
```

**Comment by JoernBerkefeld** [comment]
yup, that's how we handle that in mcdev - thank you for your patience & for using this SDK, Ivan :)
I can recommend looking into that project if you have a problem with the SDK and want to check how it might work.

your first approach would have created sth like
```xml
<Fields>...</Fields>
<Fields>...</Fields>
<Fields>...</Fields>
```

instead of 
```xml
<Fields>
  <Field>...</Field>
  <Field>...</Field>
  <Field>...</Field>
</Fields>
```

**Comment by ivanrazine** [comment]
Hey Jorn,

Yeah eventually I figured it out on my own by logging the SOAP xml code.

Could you maybe add an example of this in the readme?

Your SDK rocks btw, I’m creating a Nuxt app that uses it and it works
really well.

I’m having trouble logging the errors though in some cases

Kind regards,

Ivan Razine.

Le mer. 3 avr. 2024 à 13:38, Jörn Berkefeld ***@***.***> a
écrit :

**Comment by JoernBerkefeld** [comment]
fair point. created a new ticket to track updating the docs
